[phases]
setup = "python -m pip install --upgrade pip setuptools wheel"
install = "pip install -r requirements.txt"
start = "gunicorn --bind 0.0.0.0:$PORT app:app"

[phases.variables]
PYTHON_VERSION = "3.10"