[phases]
setup = "python -m pip install --upgrade pip setuptools wheel"
install = "pip install --no-cache-dir -r requirements.txt"
start = "gunicorn --bind 0.0.0.0:$PORT app:app"

[phases.variables]
PYTHON_VERSION = "3.10"

[build]
language = "python"  # Explicitly force Python detection